name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # You can change this to your preferred Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run TypeScript
        run: npm run build # Adjust this script to match your build command

      - name: Type Checking
        run: npm run typecheck # Adjust this script to match your TypeScript type-checking command

      - name: Linting
        run: npm run lint # Adjust this script to match your linting command
